//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CUI { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string Shareholders { get; set; }
        public string Percentages { get; set; }
    }
}
